[
    {
        type: "website",
        title: "Zocdoc: Appointment/ Search doctor App",
        isOver40: true,
        isInsured: false,
        organization: "Zocdoc",
        url: "https://www.zocdoc.com/",
        doctorLikes: 3,
        regularLikes: 5,
        tags: ["Recommended"],
        searchTerms: ["appointment", "zocdoc"],
    },
    {
        type: "website",
        title: "Tips for choosing a new primary care physician",
        isOver40: true,
        isInsured: false,
        organization: "BlueCross BlueSheild",
        url:
            "https://www.bcbs.com/five-tips-choosing-new-primary-care-physician",
        doctorLikes: 3,
        regularLikes: 5,
        tags: ["Tips"],
        searchTerms: ["tips", "primary doctor", "primary care physician"],
    },
    {
        type: "website",
        title: "5 tips to prepare for doctor’s visits",
        isOver40: true,
        isInsured: false,
        organization: "HealthCare.gov",
        url: "https://www.healthcare.gov/blog/get-ready-doctors-appointment/",
        doctorLikes: 3,
        regularLikes: 5,
        tags: ["Tips"],
        searchTerms: [
            "tips",
            "prepare",
            "doctor visit",
            "primary doctor",
            "primary care physician",
        ],
    },
    {
        type: "website",
        title: "Tips for Getting a Mammogram",
        organization: "The American Cancer Society",
        isOver40: true,
        isInsured: false,
        url:
            "https://www.cancer.org/cancer/breast-cancer/screening-tests-and-early-detection/mammograms/mammograms-what-to-know-before-you-go.html",
        doctorLikes: 3,
        regularLikes: 5,
        tags: ["Tips"],
        searchTerms: ["tips", "prepare", "mammogram"],
    },
    {
        type: "website",
        title: "What to expect when going to mammogram",
        isOver40: true,
        isInsured: false,
        organization: "The American Cancer Society",
        url:
            "https://www.cancer.org/cancer/breast-cancer/screening-tests-and-early-detection/mammograms/mammograms-what-to-know-before-you-go.html",
        doctorLikes: 3,
        regularLikes: 5,
        tags: ["Tips"],
        searchTerms: ["tips", "prepare", "mammogram", "what to expect"],
    },
    {
        type: "website",
        title: "Breast Ultrasound",
        isOver40: true,
        isInsured: false,
        organization: "The American Cancer Society",
        url:
            "https://www.cancer.org/cancer/breast-cancer/screening-tests-and-early-detection/breast-ultrasound.html",
        doctorLikes: 3,
        regularLikes: 5,
        tags: ["Test"],
        searchTerms: ["other test", "breast cancer test", "test", "ultrasound"],
    },
    {
        type: "website",
        title: "Breast MRI",
        isOver40: true,
        isInsured: false,
        organization: "The American Cancer Society",
        url:
            "https://www.cancer.org/cancer/breast-cancer/screening-tests-and-early-detection/breast-mri-scans.html",
        doctorLikes: 3,
        regularLikes: 5,
        tags: ["Test"],
        searchTerms: ["other test", "breast cancer test", "test", "mri"],
    },
    {
        type: "website",
        title: "Breast Biopsy",
        isOver40: true,
        isInsured: false,
        organization: "The American Cancer Society",
        url:
            "https://www.cancer.org/cancer/breast-cancer/screening-tests-and-early-detection/breast-biopsy.html",
        doctorLikes: 3,
        regularLikes: 5,
        tags: ["Test"],
        searchTerms: ["other test", "breast cancer test", "test", "biopsy"],
    },
    {
        type: "website",
        title: "Finding Breast Cancer During Pregnancy",
        isOver40: true,
        isInsured: false,
        organization: "The American Cancer Society",
        url:
            "https://www.cancer.org/cancer/breast-cancer/screening-tests-and-early-detection/finding-breast-cancer-during-pregnancy.html",
        doctorLikes: 3,
        regularLikes: 5,
        tags: ["Test", "pregnancy"],
        searchTerms: ["other test", "breast cancer test", "test", "pregnancy"],
    },
    {
        type: "website",
        title: "Getting Called Back After a Mammogram",
        isOver40: true,
        isInsured: false,
        organization: "The American Cancer Society",
        url:
            "https://www.cancer.org/cancer/breast-cancer/screening-tests-and-early-detection/mammograms/getting-called-back-after-a-mammogram.html",
        doctorLikes: 3,
        regularLikes: 5,
        tags: [],
        searchTerms: [
            "other test",
            "breast cancer test",
            "test",
            "called back",
            "second test",
            "Mammogram",
        ],
    },
    {
        type: "website",
        title: "How can I stay calm while waiting?",
        isOver40: true,
        isInsured: false,
        organization: "The American Cancer Society",
        url:
            "https://www.cancer.org/cancer/breast-cancer/screening-tests-and-early-detection/mammograms/getting-called-back-after-a-mammogram.html",
        doctorLikes: 3,
        regularLikes: 5,
        tags: ["Recommended"],
        searchTerms: [
            "wait for result",
            "breast cancer test",
            "waiting",
            "stay calm",
            "anxiety",
            "worry",
        ],
    },
    {
        type: "website",
        title: "Questions to Ask Your Doctor When You Have Cancer",
        isOver40: true,
        isInsured: false,
        organization: "The American Cancer Society",
        url:
            "https://www.cancer.org/treatment/finding-and-paying-for-treatment/choosing-your-treatment-team/questions-to-ask-your-doctor.html",
        doctorLikes: 3,
        regularLikes: 5,
        tags: ["Recommended"],
        searchTerms: [
            "prepare",
            "question",
            "ask doctort",
            "have cancer",
            "got cancer",
        ],
    },
    {
        type: "website",
        title: "Understanding Your Mammogram Report",
        isOver40: true,
        isInsured: false,
        organization: "The American Cancer Society",
        url:
            "https://www.cancer.org/cancer/breast-cancer/screening-tests-and-early-detection/mammograms/understanding-your-mammogram-report.html",
        doctorLikes: 3,
        regularLikes: 5,
        tags: [],
        searchTerms: [
            "read mammogram",
            "read report",
            "report",
            "mammogram",
        ],
    },
];
